---

plugins:
  - jest
  - babel

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:lodash-fp/recommended'

rules:
  no-console: 0
  lodash-fp/use-fp: 0
